### ISSUE TITLE
Parser for TPTP (logic SoftFOL)


### ISSUE THREAD

**Issue by sternk** [spechub/Hets#1191]
Reported by **till** and assigned to **sternk**
 Migrated from http://trac.informatik.uni-bremen.de:8080/hets/ticket/1191

---

probably it should be easy to re-use the THF parser
perhaps distinguish logic SoftFOL (prover SPASS) and TPTP (all other provers). Then, users can more easily recognize TPTP. Moreover, SoftFOL is a logic different from TPTP.

**Comment by tillmo** [comment]
@eugenk has implemented a new TPTP parser
