### ISSUE TITLE
change default reasoner for OWL 

### ISSUE THREAD

**Issue by fabianneuhaus** [spechub/Hets#1468]
Currently the default reasoner for OWL is SPASS. I suggest to change that to Pellet since Pellet is an OWL reasoner and currently the morphism from OWL to FOL is broken.

**Comment by tillmo** [comment]
either wait for #1876 (Pellet) or #1616 (Fact)

**Comment by mcodescu** [comment]
Solved, see https://github.com/spechub/Hets/commit/47f6d18afa5f02a98bec775b5ba7161cd4c713f4
For now Fact is set to default. We can change it once we get a prover to work.
