### ISSUE TITLE
Too many provers are shown

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1471]
When analysing the spec
```
spec strict_partial_order =
  sort elem
  pred __<__ : elem*elem
  forall x,y,z:elem
  . not x < x %(irreflexive)%
  . x < y /\ y < z => x <z %(transitive)%
  . x < y => not y < x  %(asymmetric)%  %implied
end
```
and then trying to prove, I can also select the truth tables prover, but then (no wonder) get an error
```
*** Error:
not a propositional formula: forall x : elem
. not (pred __<__ : elem * elem)((var x : elem), (var x : elem))
```
I also got Fact and Pellet as provers (with the same error message), but cannot reproduce that now. But I can reproduce it using the prover selection of ontohub.

**Comment by tillmo** [comment]
@eugenk, I have assigned this to you because it is related to https://github.com/ontohub/ontohub/pull/1263

**Comment by mcodescu** [comment]
At some point, we discussed about the possibility of displaying only the provers that are specific to the logic (e.g. Pellet and Fact for OWL) and giving the user the option of seeing other provers that are available via translation along a comorphism to a tool-supported logic (e.g. SPASS is available for OWL only by translation to CASL and then SoftFOL), say by ticking a checkbox.

**Comment by tillmo** [comment]
@mcodescu: good point, but that is another story (i.e. should be a separate issue). The present issue is about the appearance of provers in the list that are not reachable (from the theory's logic) by any comorphism.

**Comment by tillmo** [comment]
@cmaeder told me that this one is pretty easy: just `ExtModal2OWL` needs to be deleted from the list of comorphisms in `Comorphisms/LogicGraph.hs`. @eugenk, could you do this?

**Comment by eugenk** [comment]
I just tried this on an ubuntu vm and I can't reproduce the problem having the `truth tables` prover in the provers list. Do I need to install something special to get this prover?

```
❯ curl http://localhost:8000/version
v0.99, 1427728494

❯ curl http://localhost:8000/provers/http%3A%2F%2Fdevelop.ontohub.org%2Fsandbox%2Fpartial_order%2F%2Fstrict_partial_order/auto\?format\=json
{
"provers": [
 "QuickCheck",
 "isabelle_process",
 "Isabelle-jedit",
 "Isabelle-emacs",
 "eprover",
 "darwin",
 "darwin-non-fd",
 "Vampire",
 "MathServeBroker",
 "SPASS",
 "Isabellesledgehammer",
 "Isabellerefute",
 "Isabellenitpick",
 "Isabelleautomated",
 "Fact",
 "Pellet"]
}
```
I used the current version of the hets ubuntu package for this test.

**Comment by tillmo** [comment]
normal you do not need to install anything. But the problem is already to have Fact and Pellet in the list.

**Comment by eugenk** [comment]
Alright. Those two are gone with the code from the pull request.
