### ISSUE TITLE
MathServ Broken

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1491]
This is probably related to #1480.

MathServ is currently broken. In https://github.com/spechub/Hets/blob/4ba7f783ec1dc1a9f733b9d9d9a7fc2f6458e14d/SoftFOL/ProveMathServ.hs#L155, `msResponse` has the content
```
ErrorMisc "<socket: 15>: Data.ByteString.hGetLine: timeout (Operation timed out)"
```

I tested this with attempting to prove the following file with MathServ: https://raw.githubusercontent.com/ontohub/ontohub/399962bdd666b5d2d64b6fbb575d39160d64d2c1/spec/fixtures/ontologies/prove/Simple_Implications.casl
```
curl -X POST -H "Content-Type: application/json" -d '{"format":"json","include":"true","prover":"MathServeBroker"}' http://localhost:8000/prove/https%3A%2F%2Fraw.githubusercontent.com%2Fontohub%2Fontohub%2F399962bdd666b5d2d64b6fbb575d39160d64d2c1%2Fspec%2Ffixtures%2Fontologies%2Fprove%2FSimple_Implications.casl/auto
```

**Comment by cmaeder** [comment]
I could not restart the MathServ. I've sent the MathServ stuff to @tillmo so that they can set it up in Magdeburg.

**Comment by cmaeder** [comment]
Somehow the file `tomcat-users.xml` became corrupted. It seems to be fixed now, but do not know for how long.
