### ISSUE TITLE
Allow to specify input type

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1507]
If you try to evaluate a TPTP file via the Hets RESTful interface (specifying `<url>?input-type=tptp`), Hets encounters the error 
```
openFile: does not exist (No such file or directory)
```

It seems like the input-type option only allows us to use local files. This must be extended to allow the download via HTTP as well.

We need this feature for https://github.com/ontohub/ontohub/issues/1438

**Comment by eugenk** [comment]
I can't find the place where we need to change the resource fetching. I added `Debug.trace` outputs before every single occurrence of `openFile` in the Hets code, but none of them is called, when I run
```
curl http://localhost:8000/dg/http%3A%2F%2Fhost%2Fpath%2Fto%2Ftptp-file.tptp/full-theories/full-signatures?input-type=tptp
```
and Hets still prints the openFile error.

@cmaeder: Do you know, from the top of your head, where we need to intercept?

**Comment by cmaeder** [comment]
I can reproduce the error using

```
curl http://localhost:8000/dg/https%3A%2F%2Fgithub.com%2Fspechub%2FHets%2Fraw%2Fmaster%2FSoftFOL%2Ftests%2Fasym.tptp
```

or by

```
hets -v2 https://github.com/spechub/Hets/raw/master/SoftFOL/tests/asym.tptp
Reading file https://github.com/spechub/Hets/raw/master/SoftFOL/tests/asym.tptp
hets: https://github.com/spechub/Hets/raw/master/SoftFOL/tests/asym.tptp: openFile: does not exist (No such file or directory)
```

The file is actually downloaded and available in `anaString` in `Static.AnalysisLibrary`. I've no clue yet why it fails, though.

**Comment by cmaeder** [comment]
`SoftFOL.ParseTPTPAsLibDefn.parseTPTP file` calling `readFile` called from `Driver.ReadLibDefn.readLibDefn` is the problem!
