### ISSUE TITLE
TPTP proof status question

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1509]
I want to use the MPTP2078 library to evaluate my axiom selection algorithms for my master's thesis. However, I struggle with loading them into hets.

Two example files are in this gist: https://gist.github.com/eugenk/d24cd65836e2cca6ba38
Parsing the file [Simple_Implications_Group.tptp](https://gist.github.com/eugenk/d24cd65836e2cca6ba38#file-simple_implications_group-tptp), we get in the xml output the line
```xml
      <Theorem status="open" name="ga_conjunction_of_theorem">
```
while for [zfmisc_1__t92_zfmisc_1.tptp](https://gist.github.com/eugenk/d24cd65836e2cca6ba38#file-zfmisc_1__t92_zfmisc_1-tptp) we get
```xml
      <Theorem status="proven" name="t92_zfmisc_1">
```
How can Hets say that the Theorem is open in one case and already proven in the other?

For the evaluation, I need them all to be open. Otherwise the `prove` command returns with `nothing to prove`.

**Comment by cmaeder** [comment]
Hets recognizes theorems as proven if they are identical to an axiom. For conjecture `t92_zfmisc_1` the following axiom `l50_zfmisc_1` looks equal.

**Comment by eugenk** [comment]
Alright. So the static analysis already takes care of proving trivial theorems? That's good to know. Then we need to adjust the hets-xml-parser in ontohub a little. Thanks!
