### ISSUE TITLE
DG XML contains Individuals, even if OWL ontology does not

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1518]
try `hets -o xml -O . http://ontohub.org/bioportal/ADW.owl`

**Comment by mcodescu** [comment]
When opening the ontology with Protege, it has individuals, see screenshot. @tillmo do we encounter this for other ontologies, or can the ticket be closed?

![adw](https://user-images.githubusercontent.com/1632930/95542179-5f926800-09f5-11eb-92c5-89d2ef26dce0.png)

**Comment by tillmo** [comment]
you are right
