### ISSUE TITLE
THF in TPTP files can't be parsed

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1536]
When trying to analyze `Problems/AGT/AGT027^1.p` from the TPTP distribution [1], Hets fails parsing the `thf` lines.

The Files are in the follwing gist: https://gist.github.com/eugenk/351fa5899769edb8a0a3

The paths of the files are:

* Problems/AGT/AGT027^1.p
* Axioms/LCL013^0.ax

--
#### References
[1] http://www.cs.miami.edu/~tptp/TPTP/Distribution/TPTP-v6.2.0.tgz

**Comment by sternk** [comment]
I'll take a look at it sometime this week

**Comment by tillmo** [comment]
@sternk, have you managed to take a look?

**Comment by sternk** [comment]
Yes, I think I know the issues and will fix them in the coming days.

**Comment by tillmo** [comment]
good! @eugenk needs this soon for his masters thesis.

**Comment by sternk** [comment]
Ok. I will work on it tomorrow!

**Comment by tillmo** [comment]
good!

**Comment by sternk** [comment]
The problem with the parser for TPTP in the THF logic was that the StaticAnalysis was to strict - per "http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html"

> %----All symbols must be typed exactly one before use, and all atomic types
> %----must be declared (of type $tType) before use.

but in AGT027^1.p the atomic type `mu` is not declared. In 278e4304bffe418c6be5d16ffddf00de976e0b80 I have changed this to be a non-fatal error (since it is trivial to add the declaration).

Going through my open issues I noticed #1191. If this issue was actually about this (i.e. hets -in tptp not working properly) I would suggest adding SPASS and any other features of the SoftFOL-logic to the THF logic since by now SPASS natively supports tptp input (cf. http://www.spass-prover.org/download/)

> Added native TPTP syntax support, controlled by the -TPTP flag.

**Comment by sternk** [comment]
@tillmo Do you know of any reason why getting rid of the SoftFOL logic and moving the SPASS prover and the comorphisms over to THF is not a good idea?

**Comment by tillmo** [comment]
actually, SPASS can handle a bit more than TPTP, namely the DFG format. However, I am not sure how important this is. Generally I think your idea is a good idea. Maybe you could keep SoftFOL, but still move everything to THF (please add TPTP as a sublogic of THF), except from those things that really work with DFG (I think some comorphisms might end in DFG and not in TPTP). SPASS would be a prover for both THF and DFG/SoftFOL. There would be an inclusion from TPTP (as a sublogic of THF) to SoftFOL.

**Comment by sternk** [comment]
I can certainly add another sublogic to THF, but I was under the impression that http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html describes the Syntax for TPTP. Can you maybe point me to some resource which makes it clear how to define the sublogic of interest?

**Comment by sternk** [comment]
So the plan would be to remove the TPTP related parts from SoftFOL (leaving only the DFG-Syntax part and maybe the TPTP printing if that seems useful) and creating a comorphism from a suitable sublogic of THF to SoftFOL?

**Comment by tillmo** [comment]
yes. Indeed,  http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html describes the TPTP syntax. The sublogic I want would avoid thf and use only fof. Maybe it also can be called FOF.

**Comment by sternk** [comment]
Ok. I will start working in that.

**Comment by eugenk** [comment]
As far as I'm concerned with my master's thesis, this is not very urgent. I can transform those files to `.het` files like the THF example in Hets-Lib. So this issue is not very urgent from my perspective.

However, I can't work around #1544.
