### ISSUE TITLE
clarify use of the "empty.txt"

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1538]
In `PGIP.Server`, we have two places where the string `"empty.txt"` is used. This seems to be a filename for synchronisation.

Why exactly is this file there? Why is it called "empty.txt"? It seems to restrict the Hets server to one running instance per machine.

A better filename could be something like "hets-server-instance-[port-number].lock", if it is used for synchronisation.

**Comment by cmaeder** [comment]
This file is more sort of a log-file. It collects the information (IP etc.) from clients. 

Furthermore this file is used as "mask" for the permissions of tmp-files (that are usually not readable by others). Maybe I did this to be able to read the files created by user "nobody". It was easier to `copyPermissions` than to set them explicitly.

**Comment by eugenk** [comment]
Alright, thanks. Still, we should change the name to something more descriptive that doesn't conflict with multiple running Hets instances.

How about "hets-server-instance-[port-number].log"? Or even let the OS assign a tempfile to avoid conflicting names.

**Comment by cmaeder** [comment]
I suppose several hets instances would simply append to the same file, but feel free to rename it. (I was to lazy to make it a command line argument.)

These `copyPermissions` should be removed or replaced by `setPermissions` (although I failed to construct a suitable  `Permissions` constant other than by `getPermissions`)

https://hackage.haskell.org/package/directory-1.2.4.0/docs/System-Directory.html

**Comment by cmaeder** [comment]
`writeFile` creates the file with permissions from your `umask`, whereas tempfiles have only permissions for the owner (I believe).

**Comment by cmaeder** [comment]
in https://hackage.haskell.org/package/base-4.8.1.0/docs/System-IO.html
I just see that there is `openTempFileWithDefaultPermissions` that could be used instead of `openTempFile` in `Common.Utils`

**Comment by cmaeder** [comment]
I'll make a PR, soon
