### ISSUE TITLE
Hets fails after a many REST calls in short time

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1541]
In Ontohub, we make a lot of calls in short time and Hets fails with `nextSess` after a while. It seems like there are too many open sessions.

What are the `Session` and the function `nextSess` for?

**Comment by eugenk** [comment]
The calls we make are using the `prove` command, by the way.

**Comment by cmaeder** [comment]
A development graph is stored under a session key. `prove` tries to store back the changed development graph under the same key, but this seems to fail, probably because of `cleanUpCache` (for more than 20 sessions).

**Comment by eugenk** [comment]
Why is the limit set to 20? Are the DGs so big that more would have an impact on the performance (memory-wise)?

**Comment by eugenk** [comment]
Do we need the session in the REST API, anyway? At a first glance it seems to be a feature for the old webAPI.

**Comment by cmaeder** [comment]
The limit is arbitrary. Right, `prove` is not REST.

**Comment by eugenk** [comment]
Okay, so we need to actually fix this issue and can't circumvent it.

Do I understand it correctly?
1. we send a lot of `prove` commands
2. Hets analyses the files and stores the DG for each of them in the `Session`
3. Hets removes entries from the session as soon as the threshold of 20 entries is reached
4. Hets tries to actually prove something - When looking up the DG from the `Session`, it is not present.

So we need to ensure that the entry is still there. I think the best way to go is to only allow things to be cleaned as soon as the command has finished. We could add a flag to the `Session` like `sessCleanable :: Boolean` as soon as we retrieve it for the last time. What do you think?

**Comment by cmaeder** [comment]
Yes, and I would also abort some `prove` attempts if they take too long (like an hour or a day).

**Comment by eugenk** [comment]
Isn't the `timeout` parameter taking care of it?

**Comment by cmaeder** [comment]
Yes maybe.
