### ISSUE TITLE
forbid axiom labels that are equal to symbols

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1565]
for the need of this see https://github.com/ontohub/ontohub/issues/1585
Altermatively, rename labels (e.g. by adding "_1") until they are distinct to symbols. This should also be done for unions that lead to clashes.

**Comment by mcodescu** [comment]
I will forbid labels that overlap with symbol names.

**Comment by tillmo** [comment]
I think we do not need this anymore in Ontohub 2.0.
