### ISSUE TITLE
can't use Fact

### ISSUE THREAD

**Issue by mcodescu** [spechub/Hets#1569]
When trying to check consistency of a node via the RESTful API, I get ```no libFaCTPlusPlusJNI.so```.
This should be packaged with HETS.

**Comment by jelmd** [comment]
Is it possible to add an example to be able to check (i.e. just the curl call and if available some lines of the expected output to get the idea ...)?

**Comment by cmaeder** [comment]
see #1412

**Comment by mcodescu** [comment]
Thank you, works now.
