### ISSUE TITLE
rejecting two axioms does not work

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1583]
For
```
logic OWL
ontology InputSpace1 =
  <http://ontohub.org/sandbox/inconsistent.omn>
  reject Ax1, Ax2
end
```
I still get both Ax1 and Ax2 (see this using the "prove" node menu, or with "hets -o xml").

**Comment by mcodescu** [comment]
I have just committed a fix. This was caused by a workaround for converting from symb_items to strings that was not correct. The example above goes through as expected now.
