### ISSUE TITLE
avoid adding prefixes to symbols in translation OWL22CASL

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1585]
example: see #1584

**Comment by mcodescu** [comment]
Is it right that Hets generates an expanded IRI for symbols without prefixes, e.g. for the object property ```p``` in the example:
```
QN {namePrefix = "", localPart = "p", iriType = Abbreviated, expandedIRI = "http://www.hets.eu/ontology/unamed#p", iriPos = nullRange}
```
?

**Comment by tillmo** [comment]
no. After all, DOL files can also have a prefix section. This means that the OWL prefix section should be converted to a DOL prefix section. We can do this later. For now, it is urgent to have simple names for easier debugging.

**Comment by tillmo** [comment]
I have some OWL ontology that is proved inconsistent (via SPASS) with the old OWL22CASL, but not with the new one, see https://gist.github.com/tillmo/d448365b048b97fd5f00

**Comment by mcodescu** [comment]
I'd rather suspect #1584 to have caused this.

**Comment by tillmo** [comment]
no, the difference between "new" and "old" here is just your 1585 patch.

**Comment by tillmo** [comment]
btw, names like "op h-nb : Thing" are not legal CASL synatx.

**Comment by tillmo** [comment]
aha, with this replacement, I now also get an inconsistency with the new version

**Comment by mcodescu** [comment]
OK, I wanted to keep original names, I will apply an existing method that replaces non-alphanumerical symbols with "_u". Or I can modify it to add just "_", if you prefer.

**Comment by tillmo** [comment]
"u" is better in order to avoid ambiguities.

**Comment by mcodescu** [comment]
OK, it is committed.

**Comment by mcodescu** [comment]
no prefixes are added currently, fixed.
