### ISSUE TITLE
static analysis of entailment

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1588]
we need also this for the OMG meeting.
entailment e = OMS1 entails OMS2 should procude an inclusion theorem link from OMS2 to OMS1 in the development graph.

**Comment by mcodescu** [comment]
On the same branch as the analysis of extract. This goes through: 
```
logic OWL

ontology O1 = 
 Class: A
end

ontology O2 = 
 Class: A
end

entailment e = 
  O1 entails O2
end
```

**Comment by tillmo** [comment]
good, works. Can you create a pull request?

**Comment by mcodescu** [comment]
Yes, but note that this is based on the static analysis of intersections. There is a pull request for that, but solving your comment there seems rather complicated at the moment. Would it possible to turn that into an issue and merge the branch as it is for now?

**Comment by tillmo** [comment]
OK, opened an issue: #1589

**Comment by mcodescu** [comment]
see d8fad841d8b6d97d423f2f2e24c3ceaf4c177b1b
