### ISSUE TITLE
avoid parsing HTML redirections

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1620]
The call
```
hets http://ontohub.org/ref/17/meta/dol-ontology
```
leads to a parsing error, because this URL yields a 302 redirect (to https://ontohub.org/ref/17/meta/dol-ontology) and Hets tries to parse the HTML of the redirection. Instead, Hets should follow the redirection(s) and only then parse the output.

**Comment by tillmo** [comment]
The call of `wget` in `Common.Http` is alright: `wget` follows the redirection. The problem is the OWL API, which loads the URL again, but this time without following the redirection. Hence, the OWL API parser tries to parse the HTML of the redirection, which of course fails. (Try e.g. to load http://ontohub.org/ref/17/meta/dol-ontology into Protégé - this fails.)

**Comment by tillmo** [comment]
workaround: Hets should recognize the redirection and feed the OWL API with the new URL.

**Comment by tillmo** [comment]
we should also file a ticket for the OWL API

**Comment by jelmd** [comment]
Hmm, not sure if this is the root cause, however, I think https://github.com/spechub/Hets/blob/master/OWL2/java/de/unibremen/informatik/OWL2Parser.java#L53 smells. Per default the created HttpURLConnection follows redirects, but only if the protocol does not change (for security reasons). And because the protocol gets changed from http to https  ...

**Comment by jelmd** [comment]
BTW: see https://github.com/owlcs/owlapi/blob/version3/api/src/main/java/org/semanticweb/owlapi/model/OWLOntologyLoaderConfiguration.java#L168 . So adding a `config.setFollowRedirects(true);` right before https://github.com/spechub/Hets/blob/master/OWL2/java/de/unibremen/informatik/OWL2Parser.java#L60 might solve the problem for OWL api itself.

**Comment by tillmo** [comment]
@jelmd, thanks for the hint. Could you please try that?

**Comment by tillmo** [comment]
Aha, still the problem remains that some Ontohub ontologies cannot be loaded into Protégé. So perhaps we should restrict the http to https redirection to certain pages, e.g. login page?

**Comment by tillmo** [comment]
or better: only redirect from http to https for HTML pages.

**Comment by jelmd** [comment]
Can you try the 1620_owl_http_redirects branch?

**Comment by tillmo** [comment]
yes, works! Could you create a pull request please?
