### ISSUE TITLE
 hets: Static/GTheory.hs:170:12-17: Assertion failed

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1666]
When I call Hets with
```
logic OWL
ontology Family1 =
  Class: Mother  
  Individual: mary
then %implies
  Individual: mary Types: Mother
end
```
and then translate the whole library with CASL2OWL2, I get
```
hets: Static/GTheory.hs:170:12-17: Assertion failed
```
The assertion is
```
  assert (plainSign sig1 == plainSign sig2')
```

**Comment by mcodescu** [comment]
The translated signature of `sig2'` has the sorts
```
sorts Char, Thing, boolean, float, integer, negativeInteger,
      nonNegativeInteger, nonPositiveInteger, positiveInteger, string
sorts boolean, float, string < DATA; integer < float;
      nonNegativeInteger, nonPositiveInteger < integer;
      positiveInteger < nonNegativeInteger;
      negativeInteger < nonPositiveInteger

```
The difference to the signature of `sig1` is the whole bunch of datatypes. However, when translating each node individually via OWL22CASL, I get all datatypes in each resulting CASL theory.

Anyways, this should be fixed when the datatypes are added by need along the translation.

**Comment by mcodescu** [comment]
This indeed works now as expected.
