### ISSUE TITLE
error when proving OWL theorem with SPASS

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1669]
With
```
logic OWL
ontology Family1 =
  Class: Person
  Class: Woman SubClassOf: Person
  ObjectProperty: hasChild
  Class: Mother  EquivalentTo: Woman and hasChild some Person
  Individual: mary Types: Woman Facts: hasChild john
then %implies
  Individual: mary Types: Mother
end
```
when trying to prove the goal with the default prover SPASS, I get
```
hets: SuleCFOL2SoftFOL.transOPSYMB: unknown op: Qual_op_name john (Op_type Total [] Thing nullRange) nullRange
```

**Comment by mcodescu** [comment]
If I add `Individual: john` I can disprove the goal with SPASS.

**Comment by tillmo** [comment]
aha, then the problem is that the OWL static analysis does not catch the error.

Strangely enough, when choosing "disprove", I get `found no goals suitable for disprove function`. Do you have an explanation for that? (Unfortunately, due to #1666, I cannot translate the whole library to CASL and have a look what happens there.)
