### ISSUE TITLE
package Eprover 2.0

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1724]
currently, we have only 1.9 as Ubuntu packages. However, there is 2.0: http://wwwlehre.dhbw-stuttgart.de/~sschulz/E/Download.html

**Comment by jelmd** [comment]
see http://pkg.cs.ovgu.de/LNF/linux/ubuntu/15.04/ - should run on all flubuntu versions. Download and install via `dpkg -i _$debfile_` .

**Comment by tillmo** [comment]
thanks, works for me. However, we should not only provide deb packages, but a proper software repository, either via ppa or ourselves.

**Comment by jelmd** [comment]
Tend to a local repo, but need some time to find/check/eval proper howtos/documentation/SW. So postponing to later ...

**Comment by jelmd** [comment]
2.5 done somewhere in the past.
