### ISSUE TITLE
implicit instantiation works in CASL, but does not work in OWL

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1743]
```
logic CASL
spec SP [sort s] = op f:s->s
end
spec Inst = SP [sort t]
end

logic OWL
ontology O[ Class: A ] = Individual: i Types: A
end
ontology O_Inst = O[ Class: B ]
end
```
gives
```
Analyzing file /home/till/temp/param.casl as library param
logic CASL
Analyzing spec param?SP
Analyzing spec param?Inst
logic OWL
Analyzing spec param?O
Analyzing spec param?O_Inst
/home/till/temp/param.casl:10.20-10.31: *** Error:
OWL symbol(s) missing in target: {Class A}
hets: user error (Stopped due to errors)
```
The error message is generated by `Logic.Logic.inclusion`. The solution would be to implement `Logic.Logic.induced_from_to_morphism` also for OWL2.

**Comment by mcodescu** [comment]
On the branch https://github.com/spechub/Hets/tree/1743-induced-morphisms-for-OWL there is a quick-fix that makes implicit instantiation work for classes. I'll generalize this to other types of entities too, but you may want to try it and use it now.

**Comment by tillmo** [comment]
many thanks, this works for me!

**Comment by mcodescu** [comment]
See https://github.com/spechub/Hets/commit/ed031377c06f8fc8dbcdce93f869b06021937b86
