### ISSUE TITLE
Logic.morphism_union not implemented for: OWL

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1745]
This error comes for 
```
logic OWL
ontology O[ Class: A ] [ Class: B ] = Individual: i Types: A
end
ontology O_Inst = O[ Class: C ][ Class: D ]
end
```

**Comment by mcodescu** [comment]
This should unite two morphisms only if they agree on common symbols. The source and target signatures are the union of the source and target signatures respectively. Is this what we want?

**Comment by tillmo** [comment]
yes

**Comment by mcodescu** [comment]
I have committed something that needs improvements on the branch where induced_from_to_morphism is implemented, because you will need both things to make the example work.

**Comment by tillmo** [comment]
many thanks, works!

**Comment by tillmo** [comment]
could you please create a pull request for these two quick fixes?

**Comment by mcodescu** [comment]
See https://github.com/spechub/Hets/commit/ed031377c06f8fc8dbcdce93f869b06021937b86
