### ISSUE TITLE
setup own debian repo for Hets

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1761]
such that users can install Hets via apt, but without using a ppa (this will not work due to stack).

Aee also #1724

**Comment by tillmo** [comment]
see https://github.com/communtu/communtu/blob/master/app/models/deb.rb for how to set up an own repo using reprepro. Note that you do not need to care about derivatives (Xubuntu, Lubuntu...) because they do not make any difference. However, you need to care about distributions (xenial, artful, bionic, ...).

**Comment by jelmd** [comment]
Deb packages stored in an appropriate subdirectory of http://pkg.cs.ovgu.de/LNF/linux/ubuntu/ can now be added to the system via apt-get by adding an appropriate line to `/etc/apt/sources.list` or `/etc/apt/sources.list.d/${name}.list` and running `apt-get update` before. E.g.:
```
echo "deb [trusted=yes] http://pkg.cs.ovgu.de/LNF/linux/ubuntu `lsb_release -rs`/" >/etc/apt/sources.list.d/ovgu.list
```

**Comment by tillmo** [comment]
hm, this repo only contains three packages: lex, nvidia-graphics-drivers, pkgtools. Probably the URL is wrong?

**Comment by jelmd** [comment]
Nope, no other packages have been built for xenial so far.

**Comment by tillmo** [comment]
but these three packages are not related to Hets...

**Comment by jelmd** [comment]
Correct. IMHO it doesn't make sense to create a separate PPA for each project or SW we build by ourselves. Maintenance burden is too high and I can't see any benefit we would have by splitting all this stuff up.

So it should be taken as a "vendor" PPA, which contains all the packages needed by our own clients and servers incl. the ones we like to distribute/make available for org-extern resources.

**Comment by tillmo** [comment]
OK, understood.

**Comment by jelmd** [comment]
Done somewhere in the past: Use:
```
printf 'deb [trusted=yes] http://pkg.cs.ovgu.de/LNF/linux/ubuntu `lsb_release -rs`/" \
    >/etc/apt/sources.list.d/csmd.list
```
