### ISSUE TITLE
arch spec with DG node name used twice

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1769]
the DG node name `OrderFun_amalg` is used twice in
```
library Invoice_corrected
spec Nat = sort s
arch spec Warehouse =
units
  NatAlg : Nat;
  OrderFun : Nat -> Nat;
  T = OrderFun[NatAlg]
result
  OrderFun[T]
end
```

**Comment by mcodescu** [comment]
There is a fix on https://github.com/spechub/Hets/tree/1769-duplicate-node-names. It will fix the problem in this example. But it will generate duplicate names if a generic unit is applied more than once to the same list of arguments: the static analysis generates new nodes and they are named using the same convention, using the name of the generic units and of the arguments.

**Comment by tillmo** [comment]
What about the following idea for preventing duplicate node names: write a function that gets an DG and a new node name. It looks where the name has been taken already, and if so, it adds some number to the name and recursively calls itself. Otherwise, the name is just returned.

**Comment by mcodescu** [comment]
for an arch spec where `F[A]` appears both in a unit definition and in the result unit term, I get a graph with unique nodes
![dgraph](https://user-images.githubusercontent.com/1632930/32267279-ff55b56c-beea-11e7-90a0-5e805160c233.png)

**Comment by tillmo** [comment]
good, now `Hets-lib/CaseStudies/Invoice_corrected.casl` goes through #1752. Please remove the tracing and file a pull request.

**Comment by mcodescu** [comment]
The branch https://github.com/spechub/Hets/tree/1769-duplicate-node-names is missing, but the problems seem to have been solved, see https://github.com/spechub/Hets/commit/e7bd3ae7fc8b063f253c450dfb7cce6229416f3a, https://github.com/spechub/Hets/commit/3c5c7e3fbc88e305dfb8a017757da84b2565d919. I will close this, reopen if need be.

**Comment by tillmo** [comment]
I have just restored the brach, but it has already been merged to master.
