### ISSUE TITLE
New GUI based on javascript (NW.js and D3)

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1770]
Currently, the Hets GUI is based on uDrawGraph and HTk, which are both outdated and difficult to maintain. The task is to create a new Hets GUI based on modern javascript technology, namely NW.js (a framework for developing standalone GUIs using javascript) and D3 (a fancy graph layout library).

In more detail, replace the graph display interface (`UDrawGraph.Basic`, `UDrawGraph.Graph`, `UDrawGraph.Types` from https://hackage.haskell.org/package/uni-uDrawGraph) and the window management interface (`GUI.HTkUtils` from Hets) by an implementation based on D3 (graphs) and NW.js (windows).
The packages https://hackage.haskell.org/package/uni-graphs and https://hackage.haskell.org/package/uni-events etc. should be kept. uni-graphs provides some abstract interface for graph drawing, which now needs to be instantiated using D3 instead of uDrawGraph.

**Comment by tillmo** [comment]
possible alternatives for D3:  graphviz or yFiles or http://arborjs.org or http://thejit.org
possible alternatives for NW.js: https://electron.atom.io/

**Comment by tillmo** [comment]
possible alternatives for communication with Hets: uni package (see above), (interactive command line interface), RESTful interface

**Comment by jelmd** [comment]
possible alternatives for NW.js: [Swing](http://dev.cs.ovgu.de/java/jdk-1.8.0/docs/technotes/guides/swing/index.html)

**Comment by tillmo** [comment]
@jelmd: we want to use Javascript with react, not Java.

**Comment by jelmd** [comment]
ah ok. thanx.

**Comment by tillmo** [comment]
please rebase branch 1770-new_gui  on master. This eases testing the code.

**Comment by tillmo** [comment]
we now integrate Hets with Atom, see #1862
