### ISSUE TITLE
Free spec produces nodeId without nodeLabel.

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1785]
The following spec
```
library Examples/dodatek
spec ExpSemantics = sort Env
spec InstrSyntax = {}
spec InstrSemantics =
  InstrSyntax and ExpSemantics then
    free {
      op M : Env 
      }
end
```
produces a DG with a nodeId without nodeLabel. See also #1752.

**Comment by tillmo** [comment]
problem vanishes with a fresh compilation of Hets

**Comment by mcodescu** [comment]
I can reproduce the error, but Till does not get it on his machine. @eugenk could you also try and tell us what happens after a fresh compilation of Hets?

**Comment by eugenk** [comment]
A fresh complied Hets on the branch 1691-... yields:

hets: user error (Maybe.fromJust: Nothing)

**Comment by eugenk** [comment]
on master, with `-o xml`, I get:

```
hets: labDG 2
CallStack (from HasCallStack):
  error, called at ./Static/DevGraph.hs:1258:25 in main:Static.DevGraph
```

**Comment by tillmo** [comment]
my fault, I used a wrong input file. I now can reproduce the error, too. I have started some tracing on branch 1785_free_spec. This shows: the DG is created with 5 nodes within `Static.AnalysisStructured`. But then, in `Static.AnalysisLibrary`, one node is deleted again by calling `Static.ComputeTheory.computeDGraphTheories`. @mcodescu, could you please have a look?

**Comment by mcodescu** [comment]
The problem is not `Static.ComputeTheory.computeDGraphTheories` but `Static.AnalysisLibrary.shortcutUnions`. I have removed on Till's branch the call to it and now things work. I would just need to understand why this was needed in the first place.

**Comment by tillmo** [comment]
Basically, `Static.AnalysisLibrary.shortcutUnions` removes all union nodes N that
 * have exactly one outgoing link (let Out be its target node), which must be a global definition link with trivial conservativity status, and
 * have more than one incoming link (let In_1...In_n be their source nodes)
 * have no local axioms, and
 * are not the node of a named OMS.

A node is removed by replacing the links In_i-->N-->Out with links In_i-->Out (i=1..n), using the composition of the involved signature morphisms. 
The reason for doing is to make the development graph smaller and thus more readable.
We need to check the extra condition that Out has no outgoing (co)freeness link. I wonder whether such an outgoing link could also be added later (i.e. Out would be used as a referenced node in a different library). However, I think this cannot be the case: in order to have the problematic situation above, the `(co)free` must occur in the form `then (co)free {...}`. But then the extension (i.e. node Out) would also need to be part of the different library, but then the union (i.e. node N) would be the referenced node, not Out.

**Comment by tillmo** [comment]
@mcodescu, could you implement this?

**Comment by mcodescu** [comment]
Fixed, see https://github.com/spechub/Hets/commit/0c1c431111e768803ecc7ac9c2725bec9b6787b4
