### ISSUE TITLE
build PPA packages for Ubuntu 17.10

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1795]
currently, this should still work with master

**Comment by jelmd** [comment]
Got the dependencies to launchpad.net/hets's packages libghc-aterm-dev libghc-hexpat-dev libghc-uni-htk-dev libghc-uni-graphs-dev libghc-uni-udrawgraph-dev darwin spass eprover  removed? Otherwise those would need an update first.

BTW: Wasn't the plan to build for LTS releases, only?

**Comment by tillmo** [comment]
no, the dependencies were not removed.

The plan is to build the ppa for 17.10 for a last time and then switch to an own repo (necessary due to use of stack).

**Comment by jelmd** [comment]
Aha, ok. So I'll wait for the deps.

**Comment by tillmo** [comment]
I have just discussed with @eugenk that this is too compliated (see also the problems in #1803). Instead, we should follow #1761, using stack.
