### ISSUE TITLE
implement symbol kind for HasCASL

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1800]

**Comment by tillmo** [comment]
@eugenk, you had a list of logics with missing symbol kind implementation. Could you please file an isse for that?

**Comment by eugenk** [comment]
https://github.com/spechub/Hets/pull/1752#issuecomment-346734486:
> If I comment out the default implementation in `Logic.Logic`, I get a warning for missing implementation for the logics
>
> - CSMOF
> - DMU
> - Isabelle
> - OMDoc
> - QVTR
> - Temporal
> - HasCASL
> - RelationalScheme
> - CASL_DL
> - COL
> - CoCASL
> - ConstraintCASL
> - CSPCASL
> - ExtModal
> - FPL
> - Modal
> - VSE
> - Adl
> - CSL
> - DFOL
> - Framework
> - FreeCAD
> - HolLight
> - LF
> - Maude
> - QBF
