### ISSUE TITLE
"Not in scope:" compiler errors

### ISSUE THREAD

**Issue by jelmd** [spechub/Hets#1803]
Trying to compile the `master` tree but getting the following errors:
```
[757 of 804] Compiling Common.Http      ( Common/Http.hs, Common/Http.o )

Common/Http.hs:34:21: Not in scope: `parseRequest'

Common/Http.hs:47:9:
    Not in scope: data constructor `HttpExceptionRequest'

Makefile:508: recipe for target 'hets-opt' failed
make[1]: Leaving directory '/export/scratch/elkner/build/hets-0.100.0'
Makefile:901: recipe for target 'hets.bin' failed
```

**Comment by tillmo** [comment]
have you tried `rm stack; make stack`?

**Comment by jelmd** [comment]
No. I'm trying to build the fast way [in prep. for ppa], i.e. w/o stack.

**Comment by tillmo** [comment]
Hm, then you probably need to install some dependencies. @eugenk, is it still possible at all to compile the current master without stack?

**Comment by eugenk** [comment]
This error comes from https://github.com/spechub/Hets/blame/master/Hets.cabal#L65-L67. 

The debian packages for these are:
https://packages.debian.org/source/sid/haskell-http-client
https://packages.debian.org/source/jessie/haskell-http-client-tls (outdated)
https://packages.debian.org/source/sid/haskell-connection

And there is https://github.com/spechub/Hets/blame/master/Hets.cabal#L137 with the debian package:
https://packages.debian.org/source/sid/haskell-file-embed

**Comment by eugenk** [comment]
If these dependencies are installed, it should be possible to compile Hets without stack.

**Comment by jelmd** [comment]
Ehmm, we use ubuntu, i.e. there are no such packages. Anyway, I've already installed libghc-split-dev libghc-http-client-tls-dev libghc-file-embed-dev before submitting this issue. So must be something else. Perhaps a version issue? `dpkg -l | grep ghc|grep http` shows:
```
ii  libghc-http-client-dev                       0.3.8.2-1build1                            amd64        HTTP client engine
ii  libghc-http-client-tls-dev                   0.2.2-1                                    amd64        http-client backend using connection and tls libraries
ii  libghc-http-date-dev                         0.0.2-3build1                              amd64        HTTP Date parser/formatter
ii  libghc-http-dev                              1:4000.2.17-1                              amd64        GHC libraries for the Haskell HTTP client library
ii  libghc-http-types-dev                        0.8.5-1                                    amd64        Generic HTTP types (for both client and server code)
```

**Comment by eugenk** [comment]
These are too old. At least one major version behind.

**Comment by jelmd** [comment]
see #1833

**Comment by jelmd** [comment]
obsolete.
