### ISSUE TITLE
implement symbol kind for various logics

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1808]
see #1800 as a role model. Implement it for these logics (but note that some of them are built over CASL and therefore can re-use what is there to CASL):
- CSMOF
- DMU
- Isabelle
- OMDoc
- QVTR
- Temporal
- RelationalScheme
- CASL_DL
- COL
- CoCASL
- ConstraintCASL
- CSPCASL
- ExtModal
- FPL
- Modal
- VSE
- Adl
- CSL
- DFOL
- Framework
- FreeCAD
- HolLight
- LF
- Maude
- QBF

**Comment by tillmo** [comment]
@mcodescu: this one is important fpr #1752. Could we try to distribute the work among us somehow? Note that for each logic, it should only be little effort. For some logics, even one default kind might be sufficient.

**Comment by mcodescu** [comment]
I'll start and tell you where I run into problems, or logics I don't understand.

**Comment by mcodescu** [comment]
See the branch https://github.com/spechub/Hets/tree/1808-symbol-kinds. Issues:
 - in some places, I have used emptyKind, but I think this should rather be the
default in Logic.Logic. Agreed?
 - only one kind in LF. Should I call it ops or leave it to default emptyKind?
 - in HolLight we have () as type for symbols, and no instance of class Sentences???
 - in CSL the Symbol type seems to have not enough information about the symbols
as the kind is not stored. Should we change it?
 - in VSE there is a comment about how the type of symbols should be extended...
 - in Modal symbols are now just CASL symbols. Should be corrected?
 - same for ExtModal
 - same for ConstraintCASL
 - same for CoCASL
 - same for COL
 - same for CASL_DL

**Comment by tillmo** [comment]
* yes, `emptyKind' should be the default in Logic.Logic
 * in LF, I suggest `consts`
 * HolLight is indeed incomplete. @sternk, could you please help?
 * CSL: yes, should be changed
 * VSE: where is the comment?
 * Modal etc.: yes, there are new types of symbols, like modalities, of flexible ops

**Comment by mcodescu** [comment]
- I have made "emptyKind" a default. 
- changed to consts
- VSE: in Logic_VSE.hs, `morphisms and symbols need to be extended, too`

**Comment by sternk** [comment]
@tillmo - From what I remember HolLight is a very shallow logic node that
is only meant to facilitate reading dumps directly into the DG which are
then fed into the HolLight2Isabelle comorphism. What are the currently
missing pieces that would definitely need to be implemented?

**Comment by tillmo** [comment]
@sternk: we need a notion of symbol and kinf of symbol. But @mcodescu is right that we can use () and emptyKind.

**Comment by mcodescu** [comment]
Good, then the question that remains is: can we live for now with CASL symbols only for logics like Modal, CoCASL, and so on, or do we really need to work on new notions of symbols for each of these logics before #1691 can be merged? I believe this could be postponed.

**Comment by tillmo** [comment]
agreed, this can be postponed.

**Comment by mcodescu** [comment]
See https://github.com/spechub/Hets/commit/22011974b05010395c5658ca65cfdfdfcbd87985
