### ISSUE TITLE
stack setup  does not work

### ISSUE THREAD

**Issue by jelmd** [spechub/Hets#1821]
Tried to build hets in a xenial zone. However, this is a real pain and not gonna work because it tries permanently to download stuff from s3.amazonaws.com, which fails, because it uses a bunch of _unknown_ IP addresses in a round robin/random way, i.e. almost every time the OS asks the resolver to get the IP of  s3.amazonaws.com, it gets a different IP address and thus will hit the firewall pretty soon.

It should be documented, howto instruct stack to **NOT** use s3.amazonaws.com, but a different site, which has a stable IP address.

**Comment by eugenk** [comment]
The location of the packages can be configured in the stack.yaml: https://docs.haskellstack.org/en/latest/yaml_configuration/#package-indices

However, this does not help if all the packages are hosted on S3.

**Comment by tillmo** [comment]
Hence, we cannot avoid s3. Please use a more flebile scheme. See e.g. https://forums.aws.amazon.com/message.jspa?messageID=420003#420003
Or open the firewall for reading all IPs, which is standard in server administration.

**Comment by jelmd** [comment]
No - open blindly anything is not standard, even for RO, was perhaps in the 90s of last century.  It is a very bad idea. Todays standard is: Do not allow, what is not needed, and allow only endpoints you know [what you get].

Anyway, just checked: The AWS IP address gets changed every 5 seconds and the current IP address pool in use by AWS is ~ 10<sup>7</sup>+ (sub network addresses and broadcasts already excluded). So opening the FW would be a lottery - is not an option ... I could try a mirror located in china, which seems to be the only one for stack stuff with a fixed IP ;-) Anyway, will check other options ...

**Comment by jelmd** [comment]
I setup a proxy, which allows to blindly download anything from wherever the SW thinks to (for my taste kind of in-responsible, but ...).

I also made a note about the git submodule, hope you got it.

Dependencies are wrong. One does not need to install a mysql server to get hets compiled. The *-dev package inc. its deps are sufficient. I'll guess, that's the same case for PG. I'll try to puzzle it out ...

**Comment by jelmd** [comment]
xenial is not supported anymore.
