### ISSUE TITLE
add origin of sentences to GTheory

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1837]
In `Static.GTheory`, the `gTheorySens` field of a `GTheory` should also contain information about the origin DG node and sentence of each sentence in the `GTheory`. This is needed for #1836.
The location to add this information is, besides, `Static.GTheory`, `Static.AnalysisStructured`, and `Static.CompureTheory` (especially `computeLabelTheory`).

**Comment by mcodescu** [comment]
What should I store for the origin sentence of a sentence? The origin sentence might live in a different logic, so this could get complicated. I was thinking of storing the name of the origin sentence, as they are unique for each node.

**Comment by tillmo** [comment]
Yes, the name should suffice, and of course the id of the node, and the name of the development graph within the LibEnv.

**Comment by mcodescu** [comment]
The method `computeLabelTheory` takes as argument a `LibEnv` and a `DGraph`. Is there a way to get the name of the DGraph in that LibEnv, so we can save it in the origin of the sentences? Adding it as an argument (of type `LibName`) requires many changes in the functions that call, e.g. `computeLabelTheory` or `computeDGraphTheories`.

**Comment by tillmo** [comment]
I think that the `LibName` should be added during static analysis, so that you won't need it as an extra argument in `computeLabelTheory`, because it is already present in the `GTheory`s.
Another option is to always store the  `LibName` as part of the `DGraph` data structure.

**Comment by mcodescu** [comment]
Fixed, see https://github.com/spechub/Hets/commit/c632a2bb02a9b349a14ff3f684a0903e8beaad86
