### ISSUE TITLE
lists of SubPropertyChains do not work

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1861]
The following does not work:
```
logic OWL
ontology O =
  ObjectProperty: p
  ObjectProperty: r
 SubPropertyChain: 
  inverse p o r, p o r 
```
but it should be equivalent to
```
logic OWL
ontology O =
  ObjectProperty: p
  ObjectProperty: r
 SubPropertyChain: 
  inverse p o r SubPropertyChain: p o r 
```
which works

**Comment by mcodescu** [comment]
According to https://www.w3.org/TR/owl2-manchester-syntax/, section 2.5, you should not be able to write several chains after one SubPropertyChain. So it seems to me that the parser is right and the example should always be written in the second form.

**Comment by tillmo** [comment]
agreed
