### ISSUE TITLE
if restrictions on OWL are not fulfilled by a theory, OWL reasoners cannot be applied

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1863]
e.g. OWL theories are not allowed to have a property declared both as asymmetric and transitive

**Comment by tillmo** [comment]
solve this together #1865 and #931, and introduce a sublogic "OWL without restrictions", see http://ceur-ws.org/Vol-1080/owled2013_14.pdf. The OWL provers work only on OWL with restrictions.

**Comment by b-gehrke** [comment]
Solved with #2058
