### ISSUE TITLE
Create Dockerfile for Hets (Server)

### ISSUE THREAD

**Issue by ysengrimm** [spechub/Hets#1867]
Creating a Dockerfile for Hets will allow users of non Unix systems to execute a Hets server locally. Additionally Docker volumes can be used to "sync" specification files between the user's system and the server. This might provide a short term solution for using [spechub/atom-hets-integration](https://github.com/spechub/atom-hets-integration) on non Unix systems. 

Possible options:
1. use a [Ubuntu base image](https://hub.docker.com/_/ubuntu/) and install Hets from the PPA
2. build Hets from sources with a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)

Open questions:
- [x] How "sync" file ownership between the user's system and the docker environment
    - ownership of files should not be a problem, as the default user in Docker is `root` and Hets only needs to read the specification files
    - alternatively a user with the same UID as the host system user can be created ([example from rocker](https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine))

**Comment by DerProfessor** [comment]
Closing this issue because #1868 is merged.
