### ISSUE TITLE
Ubuntu PPA packages for 16.04 and 18.04 are not working

### ISSUE THREAD

**Issue by ysengrimm** [spechub/Hets#1871]
Currently the package for Ubuntu 16.04 requires the workaround described in #1869 and the Ubuntu 18.04 package is empty and doesn't install anything.

While the workaround for 16.04 ist working the (new) user experience is quite bad.

**Comment by jelmd** [comment]
Haven't checked yet, but you can use the same workaround described in #1869 for bionic. Just replace in `/etc/apt/sources.list.d/csmd.list` the 16.04 with `18.04` and run `apt update ...`.

**Comment by jelmd** [comment]
Hmmm, can you try to purge all of them before retrying the install?

**Comment by jelmd** [comment]
Fixed with a43b74bb68e7f369b9a2a8bfc93747136fc23385 and latest launchpad builds.
