### ISSUE TITLE
Hets (not hets-server) package ist missing from the PPA

### ISSUE THREAD

**Issue by ysengrimm** [spechub/Hets#1873]
The `hets` package is missing from the PPA on Ubuntu 18.04 and 16.04, only the `hets-server` package is available.

**Comment by jelmd** [comment]
There is no _hets_ package, and no intention to create one. The only meta-packages are _hets-desktop-all_ and _hets-server-all_, which bundle _hets-provers_ and _pellet_ . These packages are missing for bionic, because the related dependencies are not available yet.

**Comment by tillmo** [comment]
which dependencies are not available yet? how would they become available?

**Comment by jelmd** [comment]
a) See debian/control in https://launchpad.net/~hets/+archive/ubuntu/hets/+sourcefiles/hets-metapkg-src/1.0.5-1.16.4/hets-metapkg-src_1.0.5.orig.tar.xz
b) either by distro or via PPA
