### ISSUE TITLE
provide bionic and focal version of prover packages

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1876]
The packages edarwin, ekrhyper, isabelle, leo2, pellet, satallax, yices and zchaff are available for older Ubuntu versions, but not for bionic. Please package them for bionic.

**Comment by tillmo** [comment]
and please also package them for focal fossa.

**Comment by jelmd** [comment]
Just the same [old] versions from previous builds? Or latest version [if there is one avail.]?

**Comment by jelmd** [comment]
BTW: The TBD hets-prover packages lists cvc3, darwin, edarwin, eprover, fact++, hol-light, maude, minisat, spass, z3. When we have cvc4 is cvc3 still needed? When we have e-darwin, is darwin still needed? All others except eprover can be satisfied via default ubuntu repos.

**Comment by tillmo** [comment]
Please prefer the latest versions. cvc3 is not needed if we have cvc4. However, darwin and e-darwin should both be there.

**Comment by jelmd** [comment]
Done. Just install hets-provers, or hets-desktop-all, or hets-server-all. For isabelle just follow the install instruction provided by its maintainers.

**Comment by tillmo** [comment]
have just tried it and done some proofs, great!

**Comment by mcodescu** [comment]
This is really nice, I've never had so many provers!

**Comment by tillmo** [comment]
aha, @jelmd, could you please provide this also for rest.hets.eu?

**Comment by jelmd** [comment]
You mean, install hets-provers on rest... ?

**Comment by tillmo** [comment]
yes, please.

**Comment by jelmd** [comment]
Done.

**Comment by tillmo** [comment]
great. many thanks!
