### ISSUE TITLE
in omn file, <iri> can lead to umatched pattern

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1893]
With the *.omn file
```
Prefix: : <http://www.ontohub.org/godp/>
Ontology: <Role1>
Class: Role
```
I get
```
hets: OWL2/XML.hs:113:11-44: Irrefutable pattern failed for pattern (np, ':' : nlp)
```
If I omit the angle braces around `Role1`, it works (but then the ontology is named `//purl.obolibrary.org/obo/TEMP`, which is also strange).
I am not sure if `<Role1>` is allowed here, but if not, this should be reported properly.

**Comment by tillmo** [comment]
The example works now, but the irrefutable pattern should be caught.

**Comment by mcodescu** [comment]
#1894 fixed this, there is another issue that should have a different ticket.
