### ISSUE TITLE
Hets cannot parse large OWL files

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1935]
The Chebi ontology needs more than 400GB RAM to be parsed and translated to FOL.

**Comment by tillmo** [comment]
Here the command that I have used:
```
hets +RTS -M400G -p -RTS -t OWL22CASL:CASL2TPTP_FOF -o tptp -v2 chebi.owl
```
You can get `chebi.owl` e.g. [here](https://www.ebi.ac.uk/ols/ontologies/chebi), size is 541MB.
It would be good to try out mere parsing and analysis first, and then the translation separately.

**Comment by mcodescu** [comment]
Hets (used to ) parse(d) succesfully larger ontologies, e.g. from Bioportal. Have you tried to do some profiling?

**Comment by tillmo** [comment]
OK, just parsing and analysing takes about 7 minutes and 36GB of RAM.

**Comment by mcodescu** [comment]
Protégé also has problems opening the file, at least on my laptop:
```
Loading ontology from file:/home/mcodescu/Downloads/chebi.owl 
Finished loading file:/home/mcodescu/Downloads/chebi.owl 
An error occurred whilst loading the ontology at file:/home/mcodescu/Downloads/chebi.owl. 
Cause: GC overhead limit exceeded 
```

**Comment by fabianneuhaus** [comment]
@mcodescu That's a well-known problem with Protege. You need to increase the heap size. 

https://protegewiki.stanford.edu/wiki/ChangingTheHeapSize

**Comment by mcodescu** [comment]
@fabianneuhaus: thank you, I have tried to follow a different instruction and that did not work.

@tillmo: it seems to me that my hunch was wrong and the parser does not have a bug caused by some special form that the sentences of the ontology have. The most time and space is spent in comparisons and unions. We encountered a similar problem when we wanted to align the ontologies from Bioportal.

**Comment by tillmo** [comment]
Do you think that the comparisons and unions are needed for static analysis, or for translation, or both?
I just have realised that my report of a successful static analysis needing 36GB RAM and 7 minutes might have been premature. I did not generate any output, so due to lazy evaluation, it might be that Hets has not even built the whole signature.

**Comment by mcodescu** [comment]
I can only guess for now (I believe both creating the OWL signature and its translation). I think it would be better instead to do profiling for just parsing and analysing the ontology, and then for translation (or with translation). Yes, you could also add an output step to make sure the signatures get evaluated (some tracing message should do).

**Comment by mcodescu** [comment]
And union seems to be used for translation (profiling should help confirm this).

**Comment by mcodescu** [comment]
One very generic idea, I couldn't put my finger on the right spot for now: use strict data structures such that no unevaluated thunks eat up the memory.

**Comment by mcodescu** [comment]
In `OWL22CASL.mapSign`, try replacing `foldr` with `Data.List.foldl'` - this could impact on the memory consumption.

**Comment by mcodescu** [comment]
#1970 fixed this
