### ISSUE TITLE
switch to gtk3 is incomplete

### ISSUE THREAD

**Issue by jelmd** [spechub/Hets#1966]
Commit cf5aedf is incomplete wrt. non-stack build and debian pkg dependencies - see https://github.com/spechub/Hets/tree/gtk3_fixes .

Also the non-stack build needs to be fixed on all Ubuntu LTS. E.g. on xenial it fails with:
```
[576 of 869] Compiling GUI.GtkUtils     ( GUI/GtkUtils.hs, GUI/GtkUtils.o )

GUI/GtkUtils.hs:146:3:
    Not in scope: `windowSetTitle'
    Perhaps you meant one of these:
      `windowTitle' (imported from Graphics.UI.Gtk),
      `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:299:3:
    Not in scope: `windowSetTitle'
    Perhaps you meant one of these:
      `windowTitle' (imported from Graphics.UI.Gtk),
      `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:345:3:
    Not in scope: `windowSetTitle'
    Perhaps you meant one of these:
      `windowTitle' (imported from Graphics.UI.Gtk),
      `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:405:3:
    Not in scope: `windowSetTitle'
    Perhaps you meant one of these:
      `windowTitle' (imported from Graphics.UI.Gtk),
      `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:420:7: Not in scope: `onClicked'

GUI/GtkUtils.hs:429:3: Not in scope: `onClicked'

GUI/GtkUtils.hs:466:3:
    Not in scope: `afterSelectionChanged'
    Perhaps you meant one of these:
      `fileSelectionChanged' (imported from Graphics.UI.Gtk),
      `afterSelectionDone' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:474:9:
    Not in scope: `afterSelectionChanged'
    Perhaps you meant one of these:
      `fileSelectionChanged' (imported from Graphics.UI.Gtk),
      `afterSelectionDone' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:477:3: Not in scope: `onClicked'

GUI/GtkUtils.hs:478:3: Not in scope: `onClicked'

GUI/GtkUtils.hs:479:3: Not in scope: `onClicked'
```
or similar on bionic:
```
[670 of 869] Compiling GUI.GtkUtils     ( GUI/GtkUtils.hs, GUI/GtkUtils.o )

GUI/GtkUtils.hs:146:3: error:
    * Variable not in scope:
        windowSetTitle :: MessageDialog -> String -> IO a4
    * Perhaps you meant one of these:
        `windowTitle' (imported from Graphics.UI.Gtk),
        `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:299:3: error:
    * Variable not in scope:
        windowSetTitle :: Dialog -> String -> IO a0
    * Perhaps you meant one of these:
        `windowTitle' (imported from Graphics.UI.Gtk),
        `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:345:3: error:
    * Variable not in scope:
        windowSetTitle :: Window -> String -> IO a5
    * Perhaps you meant one of these:
        `windowTitle' (imported from Graphics.UI.Gtk),
        `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:405:3: error:
    * Variable not in scope:
        windowSetTitle :: Dialog -> String -> IO a6
    * Perhaps you meant one of these:
        `windowTitle' (imported from Graphics.UI.Gtk),
        `windowGetSize' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:420:7: error:
    Variable not in scope: onClicked :: Button -> IO () -> IO a7

GUI/GtkUtils.hs:429:3: error:
    Variable not in scope: onClicked :: Button -> IO () -> IO a8

GUI/GtkUtils.hs:466:3: error:
    * Variable not in scope:
        afterSelectionChanged
          :: TreeSelection -> IO () -> IO (ConnectId TreeSelection)
    * Perhaps you meant one of these:
        `fileSelectionChanged' (imported from Graphics.UI.Gtk),
        `afterSelectionDone' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:474:9: error:
    * Variable not in scope:
        afterSelectionChanged
          :: TreeSelection -> IO () -> IO (ConnectId TreeSelection)
    * Perhaps you meant one of these:
        `fileSelectionChanged' (imported from Graphics.UI.Gtk),
        `afterSelectionDone' (imported from Graphics.UI.Gtk)

GUI/GtkUtils.hs:477:3: error:
    Variable not in scope: onClicked :: Button -> IO () -> IO a1

GUI/GtkUtils.hs:478:3: error:
    Variable not in scope: onClicked :: Button -> IO () -> IO a2

GUI/GtkUtils.hs:479:3: error:
    Variable not in scope: onClicked :: Button -> IO () -> IO a3
```
Any hints?

**Comment by tillmo** [comment]
@TpmKranz, please have a look.

**Comment by TpmKranz** [comment]
I think `windowSetTitle` was introduced in gtk2hs 0.12.4 with this commit: https://github.com/gtk2hs/gtk2hs/commit/06eac4c8a804a1a91736b479aaa5546d04bc6dd2
With #1939, I added `gtk-0.15.5` as a stack.yaml extra-dep, but left `gtk >= 0.11.2` in Hets.cabal as a build-dep. Maybe there is a version of that library that satisfies >= 0.11.2 but is also < 0.12.4 and is somehow preferred in the build process?
Xenial's libghc-gtk3-dev is at 0.14.0, though and Bionic's at 0.14.8 so I can't imagine why these symbols aren't there. Maybe Ubuntu generate their `chi`s with `DISABLE_DEPRECATED` enabled? But then again, this would've happened before, no?
#1939 hasn't added `windowSetTitle` and removing `import Graphics.UI.Gtk.Glade` shouldn't have removed its definition.
Maybe try raising the version bound of gtk in Hets.cabal?

**Comment by jelmd** [comment]
Please make sure, that it builds with the packages provided by the distribution unless there is a very good reason, which justifies all the hard work and pain to create, build and overwrite it. xenial uses gtk2hs-buildtools 0.13.0.5-1 so I would be nice to make it compatible with this version as well.

**Comment by tillmo** [comment]
@jelmd how can one reproduce the error?

**Comment by TpmKranz** [comment]
Looking at https://github.com/spechub/Hets/commit/4839a44d3ce2e89a3b30119b5b9759000c63c4b4, we think it may be possible that replacing libghc-glade-dev with libghc-gtk3-dev got rid of the deprecated symbols by dropping the dependency on libghc-gtk-dev.
Did you try rolling back the changes from #1939 to see whether they have anything to do with this problem?

**Comment by jelmd** [comment]
@tillmo reproduction: Just install the dependencies (see e.g. https://launchpad.net/~hets/+archive/ubuntu/hets?field.series_filter=bionic on a bionic driven box (e.g. r)), checkout the branch ` gtk3_fixes` and e.g. `fakeroot make binary` (this is, what launchpad would do) or simply do a `make hets` - this should build the desktop variant of hets, only. If libghc-gtk-dev is installed on the system, make sure you `apt-get purge libghc-gtk-dev` it.

For convenience the package list for bionic:
Shipped by Ubuntu:
`gnupg2 git ant openjdk-8-jdk-headless perl-base tar xz-utils zip ghc libghc-haxml-dev libghc-tar-dev libghc-http-dev libghc-warp-dev libghc-wai-extra-dev libghc-fgl-dev libghc-xml-dev texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk libghc-split-dev libghc-file-embed-dev libghc-monad-logger-dev libghc-yaml-dev libghc-esqueleto-dev libghc-gtk3-dev libghc-http-client-dev libghc-http-client-tls-dev libghc-microlens-dev libghc-microlens-th-dev libghc-persistent-dev libghc-persistent-template-dev libghc-persistent-postgresql-dev libghc-persistent-sqlite-dev`
Shipped via launchpad:
`libghc-list-dev libghc-hexpat-dev libghc-aterm-dev libghc-uni-util-dev libghc-uni-events-dev libghc-uni-posixutil-dev libghc-uni-reactor-dev libghc-uni-htk-dev libghc-uni-graphs-dev libghc-uni-udrawgraph-dev`

It does not work on focal yet, because the `libghc-uni-graphs-dev` and `libghc-uni-udrawgraph-dev` is missing.

**Comment by jelmd** [comment]
@TpmKranz: Just comment out https://github.com/spechub/Hets/blob/gtk3_fixes/var.mk#L80 - i.e. build without `-DGTKGLADE` or just building the server (which drops this defintion) works.

**Comment by TpmKranz** [comment]
@jelmd: Now we know that the build process won't complain about missing gtk symbols if we don't as for gtk components to be compiled. :ok_hand: 
Regarding my question: I wanted to build hets according to your instructions to see whether it compiles at https://github.com/spechub/Hets/tree/f4ac445efe27b1d7cccfdd275715d33b74a744be with the system libraries, but since the ppa for bionic doesn't have all the dependencies anymore, I had to try it under xenial.
After `dpkg --add-architecture i386; apt-add-repository ppa:hets/hets; apt update; [creating a ksh93 dummy package because xenial only has ksh]; apt install hets-desktop; apt-add-repository -s "deb http://ppa.launchpad.net/hets/hets/ubuntu xenial main"; apt update; apt build-dep hets-desktop`, `make hets` fails with:
```
GUI/GraphAbstraction.hs:46:8:
    Could not find module `Events.Destructible'
    Use -v to see a list of the files searched for.

GUI/GraphAbstraction.hs:47:8:
    Could not find module `Events.Synchronized'
    Use -v to see a list of the files searched for.

GUI/HTkGenericATP.hs:29:8:
    Could not find module `HTk.Toolkit.SpinButton'
    Use -v to see a list of the files searched for.

GUI/HTkGenericATP.hs:30:8:
    Could not find module `HTk.Toolkit.Separator'
    Use -v to see a list of the files searched for.

GUI/HTkGenericATP.hs:31:8:
    Could not find module `HTk.Devices.XSelection'
    Use -v to see a list of the files searched for.

GUI/HTkGenericATP.hs:32:8:
    Could not find module `HTk.Widgets.Space'
    Use -v to see a list of the files searched for.

GUI/HTkUtils.hs:41:8:
    Could not find module `HTk.Toplevel.HTk'
    Use -v to see a list of the files searched for.

GUI/HTkUtils.hs:42:8:
    Could not find module `HTk.Toolkit.ScrollBox'
    Use -v to see a list of the files searched for.

GUI/HTkUtils.hs:43:8:
    Could not find module `HTk.Toolkit.SimpleForm'
    Use -v to see a list of the files searched for.

GUI/HTkUtils.hs:44:8:
    Could not find module `HTk.Toolkit.TextDisplay'
    Use -v to see a list of the files searched for.

GUI/HTkUtils.hs:45:8:
    Could not find module `HTk.Toolkit.FileDialog'
    Use -v to see a list of the files searched for.

GUI/ShowGraph.hs:29:8:
    Could not find module `Reactor.InfoBus'
    Use -v to see a list of the files searched for.

GUI/ShowLogicGraph.hs:19:8:
    Could not find module `HTk.Toolkit.DialogWin'
    Use -v to see a list of the files searched for.

GUI/UDGUtils.hs:17:8:
    Could not find module `UDrawGraph.Graph'
    Use -v to see a list of the files searched for.

GUI/UDGUtils.hs:18:8:
    Could not find module `UDrawGraph.Basic'
    Use -v to see a list of the files searched for.

GUI/UDGUtils.hs:19:8:
    Could not find module `Graphs.GraphDisp'
    Use -v to see a list of the files searched for.

GUI/UDGUtils.hs:20:8:
    Could not find module `Graphs.GraphConfigure'
    Use -v to see a list of the files searched for.

Taxonomy/AbstractGraphView.hs:58:18:
    Could not find module `UDrawGraph.Types'
    Use -v to see a list of the files searched for.
```
Doesn't matter whether I check out f4ac445efe27b1d7cccfdd275715d33b74a744be, 57443996823acd60e23eeafd0a3e3e6d3afab342 (before my changes), master or gtk3_fixes, the error stays the same.
I even tried to install all the packages mentioned in your comment, but to no avail. Did I do anything wrong?

**Comment by jelmd** [comment]
Looks like you are missing the related uni-* packages. Can you make sure, that you have installed the mentioned packages above using `apt-get install ...`? (For release < focal replace ksh93 with ksh, yepp).

If you need something which works, check out `v0.104.1`, purge the `libghc-gtk3-dev` and install the `libghc-glade-dev` package.

**Comment by TpmKranz** [comment]
I made sure to replace `apt` with `apt-get` in every command, but no dice.
v0.104.1 gives me the same errors; the uni-* libraries are still missing, even though I explicitly installed the corresponding packages by copy-pasting your list (iirc, they were installed by as `build-dep hets-desktop` before, but I've tried installing them manually just to be sure). Did you try compiling under xenial?

**Comment by jelmd** [comment]
Hmm, strange. I guess you did an `apt-get update` before the install. I pushed the packages to our local repo. Can you:
```
apt-get purge libghc-esqueleto-dev libghc-http-client-dev libghc-http-client-tls-dev libghc-microlens-dev libghc-microlens-th-dev libghc-persistent-dev libghc-persistent-template-dev libghc-persistent-postgresql-dev libghc-persistent-sqlite-dev libghc-list-dev libghc-hexpat-dev libghc-aterm-dev libghc-uni-util-dev libghc-uni-events-dev libghc-uni-posixutil-dev libghc-uni-reactor-dev libghc-uni-htk-dev libghc-uni-graphs-dev libghc-uni-udrawgraph-dev

apt-get purge libghc-gtk3-dev
apt-get purge libghc-glade-dev

apt-get autoremove

printf 'deb [trusted=true] http://pkg.cs.ovgu.de/LNF/linux/ubuntu 16.04/\n' >/etc/apt/sources.list.d/csmd.list
mv  /etc/apt/so/etc/apt/sources.list.d/hets.list /etc/apt/so/etc/apt/sources.list.d/hets.list.old
# and make sure ppa.launchpad.net does not appear in any  /etc/apt/sources.list.d/* or  /etc/apt/sources.list

apt-get update

apt-get install libghc-esqueleto-dev libghc-http-client-dev libghc-http-client-tls-dev libghc-microlens-dev libghc-microlens-th-dev libghc-persistent-dev libghc-persistent-template-dev libghc-persistent-postgresql-dev libghc-persistent-sqlite-dev libghc-list-dev libghc-hexpat-dev libghc-aterm-dev libghc-uni-util-dev libghc-uni-events-dev libghc-uni-posixutil-dev libghc-uni-reactor-dev libghc-uni-htk-dev libghc-uni-graphs-dev libghc-uni-udrawgraph-dev

# depending on the version either
apt-get install libghc-gtk3-dev
# OR
apt-get install libghc-glade-dev

make hets
```

**Comment by jelmd** [comment]
Hmmm, just tried the launchpad versions - with those packages I get the same errors as you, so I'll trigger a rebuild and see, whether this fixes the uni-* problem. This probably takes the whole night, because one usually needs to wait 15..30 min to get the build started, and about 30 min to get the package published => ~ 1h/package because one needs to wait 'til the previous one got published, otherwise one ends up with an old copy  ...

**Comment by jelmd** [comment]
BTW: You mentioned, that some packages are n/a. Which ones? Perhaps we have a similar problem over there as well ...

**Comment by jelmd** [comment]
Launchpad was faster than expected - relevant packages got rebuild. Do an `apt-get update` and an `apt-get upgrade` and you'll get the error described above (or non for v0.104.1).

**Comment by jelmd** [comment]
Yepp, fixed. focal packages are now available via launchpad. But see  #2064 :(
