### ISSUE TITLE
correct IRI parser

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1988]
ask @jannahastings about IRI syntax

**Comment by b-gehrke** [comment]
The java OWL API parser is not that strict than the one in HETS. If parsing fails, by default, it then stores the whole IRI String as prefix [as seen here](https://github.com/owlcs/owlapi/blob/76b9ef6d549a32512ab39ca01d11f62d6cf8a2ba/api/src/main/java/org/semanticweb/owlapi/model/IRI.java#L91). This means in particular, that the IRI `www.w3.org/1999/02/22-rdf-syntax-ns#` gets parsed although it hasn't any prefix/scheme, which is the reason, the HETS parser fails.

Relevant parts of the java parser:
 - [parsing abbreviated IRI](https://github.com/owlcs/owlapi/blob/76b9ef6d549a32512ab39ca01d11f62d6cf8a2ba/parsers/src/main/java/org/semanticweb/owlapi/functional/parser/OWLFunctionalSyntaxParser.java#L259) which calls
 - [getIRI](https://github.com/owlcs/owlapi/blob/76b9ef6d549a32512ab39ca01d11f62d6cf8a2ba/parsers/src/main/java/org/semanticweb/owlapi/functional/parser/OWLFunctionalSyntaxParser.java#L45) which calls
 - ["constructor"-Methode for IRI](https://github.com/owlcs/owlapi/blob/76b9ef6d549a32512ab39ca01d11f62d6cf8a2ba/api/src/main/java/org/semanticweb/owlapi/model/IRI.java#L91)

**Comment by b-gehrke** [comment]
The current IRI Parser(s) of HETS cannot parse the following IRI's whereas the java OWL API Parser can. They originate from  [biopartal ontologies](https://ontohub.com/bioportal) converted to Functional Syntax using [`robot convert`](https://robot.obolibrary.org/convert.html)

- `<urn:HSDBv1.0:[IND/IDE]_.Grantor>` (unexpected character `'['`) (BRIDG.owl:74148)
- `<http://www.semanticweb.org/pallabi.d/ontologies/2014/2/untitled-ontology-11#KB-CH[R]-8-5>` (unexpected character `'['`) (MCCL.owl:20)
- `<www.w3.org/1999/02/22-rdf-syntax-ns#>` (CANCO.owl:4) (the parser is expecting it to start with a scheme like "http://")

**Comment by b-gehrke** [comment]
@tillmo @mcodescu The above examples also include CURIEs enclosed in angle brackets which defines them as absolute IRIs. How should we handle this?

**Comment by tillmo** [comment]
yes, absolute IRIs in angle brackets should be covered, such that the examples go through.

**Comment by b-gehrke** [comment]
So the IRI/CURIE `<urn:HSDBv1.0:[IND/IDE]_.Grantor>` should be parsed as an **absolute** IRI with the following structure?
```
scheme: urn:HSDBv1.0
no authority
path: [IND/IDE]_.Grantor
query: ""
fragment: ""
prefix: ""
isAbbrev: False
```

**Comment by tillmo** [comment]
oh, I thought that CURIEs were forbidding in angle brackets and one would need to use square brackets. But I remember that we want to cover evering that the OWL API covers, so yes, then  `<urn:HSDBv1.0:[IND/IDE]_.Grantor>` should be parsed as CURIE.

**Comment by b-gehrke** [comment]
Parse it as
```
scheme: urn
authority: HSDBv1.0
path: [IND/IDE]_.Grantor
query: ""
fragment: ""
prefix: ""
isAbbrev: False
```
