### ISSUE TITLE
Allow MS Snippets in .dol file

### ISSUE THREAD

**Issue by b-gehrke** [spechub/Hets#2023]
Part of #1945 
With AS being the new default language, MS snippets in .dol files must be marked as such. Implement support for this.

**Comment by mcodescu** [comment]
The following file goes through on the main Hets branch:
```
logic OWL serialization Manchester

ontology GradedRels 
= Class: S
  Class: T
  ObjectProperty: p Domain: S Range: T
  Class: Val                         
  ObjectProperty: hasVal Domain: T Range: Val
  Class: T SubClassOf: hasVal some Val
  ObjectProperty: pv Domain: S Range: T SubPropertyOf: p
  Individual: v Types: Val
 ```
but on branch 2015_update_OWL2_printers_to_swrl_rules, I get a parsing error inside the DOL ontology. It looks to me as though everything is almost working (i.e. we can parse serializations and we get an error if we write something there that's not recognized), we just need to adjust the DOL static analysis for serializations to set MS as current syntax.
