### ISSUE TITLE
use FaCT++ binary

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2056]
The fact++ Ubuntu package contains `/usr/bin/FaCT++` and this should be used instead of `OWLFact.jar`.

**Comment by b-gehrke** [comment]
The binary requires the goal and entailment in a special syntax. There are dynamically linked libraries including java bindings which is currently used. It makes more sense to stick with this and fix the current implementation.
The java bindings of Fact++ only support owlapi version 4. In #2038 the owlapi version in hets was updated to 5. Hence, the current state cannot work. Going back to version 4 works, however.
