### ISSUE TITLE
Change of NeSy pattern syntax

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2075]
Currently, we can write `class`, `class[id]` or `id`. Please switch to `class`, `id : class`, because this conforms better with OWL2 ABox syntax. (The third option with `id` should go.)

**Comment by b-gehrke** [comment]
Therefore, the grammar is:
```
<SPEC>  ::= <PATH> { <PATH> }
<PATH>  ::= <NODE> { "->" <NODE> }  ";"
<NODE>  ::= [ <ID> ":" ] <CLASS>
<ID>    ::= <IRI>
<CLASS> ::= <IRI>
<IRI>   ::= <FULL_IRI> | <CURIE>
```

With required white spaces between (non-)terminals, `{}` meaning "zero or more", and `[]` meaning "zero or one". A `<FULL_IRI>` is expected to be enclosed in angle brackets, and for a `<CURIE>` with empty prefix, the colon can be omitted.

Correct?
