### ISSUE TITLE
Check that classes used in NeSy patterns have been declared

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2076]
During static analysis, check that classes used in NeSy patterns have been declared in the OWL2 ontology, that is, that they occur in the `owlClasses` of the signature.

**Comment by b-gehrke** [comment]
I suggest that we first switch to IRIs in the abstract syntax. Otherwise the `Token`s need to be parsed and expanded in static analysis creating much complexity and code that gets obsolete when switching to IRIs.

**Comment by mcodescu** [comment]
I agree with Björn here.

**Comment by tillmo** [comment]
see #2083 wait for this
