### ISSUE TITLE
support of OWL ontologies broken on rest.hets.eu 

### ISSUE THREAD

**Issue by fabianneuhaus** [spechub/Hets#2091]
If one submits the sample OWL ontology on rest.hets.eu
one gets the following error message: 

*** Error:
process stop! ExitSuccess
Logging configuration class "JulConfig" failed
java.lang.ClassNotFoundException: JulConfig

I did not explore whether this is an issue for a local installation of hets. 

Since the rest.hets.eu interface is by far the most user friendly way to use Hets (and, thus, the most popular) and OWL is the most important ontology language, I would suggest to treat this issue with high priority.

**Comment by tillmo** [comment]
works now again
