### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2108]
Build a python interface, using e.g. [hyphen](https://github.com/tbarnetlamb/hyphen). Start with the core #2107 API #1790. The python interface could be used to interface Hets with https://github.com/gavel-tool and to build new interfaces, like a new GUI.

**Comment by b-gehrke** [comment]
### Notes for hyphen
#### Building it:
- A PR prepares an automatic build for debian
	- not yet approved, but being actively review
- Systemwide installation not included
	- Build setup.py for local pip installation?
	- Extend import path env variable `PYTHONPATH`  to  build dir?
	- Symlinking build dir to python import paths?
		
#### Things to keep in mind:
- Parent modules
	- In python, when we import a module a.b.c, we necessarily also import the packages a and a.b first
	- In Haskell those package must not exist
	- Such packages must be added to `hyphen.importing.EXPECTED_EMPTY` manually
	- For example in Hets the `Common` namespace
		
#### Library
- Hyphen loads installed modules or source files.

> In general, the preferred way of accessing Haskell code from Python via hyphen is to install the Haskell code as a ghc-pkg visible library; such libraries can always be directly imported into Python with hyphen (as we have been doing so far).

- Hets needs to be library as well (at least parts needed for core API)

**Comment by b-gehrke** [comment]
Is building a GUI still the best case? Do a quick research for technology e.g. GI, Qt
