### ISSUE TITLE
fix error handling in Static.AnalysisArchitecture


### ISSUE THREAD

**Issue by sternk** [spechub/Hets#226]
Reported by **till** and assigned to **mcodescu**
 Migrated from http://trac.informatik.uni-bremen.de:8080/hets/ticket/226

---

in `Static.AnalysisArchitecture`, EmptyNode $ error ... should be replaced with local env.

**Comment by mcodescu** [comment]
@tillmo I thought the following specification would require the change to be made
```
spec S = sort s

spec T = sort t

arch spec ASP =
 units 
  F : S -> T;
  A : S;
  B : {T with s |-> u} given A
 result B
```
but I got the correct error instead:
```
*** Error:
attempt to rename the following symbols from the local environment:
{sort s}
```
Do you have an example of a unit translation that causes the error `error "Static.AnalysisArchitecture"` to be thrown in `anaUnitTerm`?

**Comment by tillmo** [comment]
No. If the symbol is in the local env, it cannot be renamed and you get the error that you have reported. If not, it can be renamed and there is no problem.

Hence, I think that this one can be closed.
